### ISSUE TITLE
Feedback on week 12 project progress for CS2113T-W12-3

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-W12-3/main#131]
## Team progress for mid-`v1.4`
* Milestones setup:
   * [x] Milestone `v1.4` setup(:heavy_check_mark: well done!)
* Milestone `v1.4` properly managed:
   * [ ] A suitable deadline 2019-11-12 set(:exclamation: try to do by next milestone)
   * [x] Issues allocated to it e.g., https://github.com/AY1920S1-CS2113T-W12-3/main/pull/129 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/126 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/125 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/124 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/123 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/122 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/121 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/114 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/111 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/108 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/107 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/105 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/103 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/101 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/100 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/94 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/92 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/56 (:heavy_check_mark: well done!)
## Individual progress of @alex-teo for mid-`v1.4`
* [ ] Merged updates to code (Java/FXML) files during the past 2 weeks (:exclamation: try to do by next milestone)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-W12-3/main/issues/124 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/123 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/122 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/114 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @amirazhar for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-W12-3/main/issues/126 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/125 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/111 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/108 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/105 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/92 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @amoschan97 for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-W12-3/main/issues/103 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/100 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/94 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/56 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @zkchang97 for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-W12-3/main/pull/129 https://github.com/AY1920S1-CS2113T-W12-3/main/pull/129 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/121 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/107 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @wyinnnn for mid-`v1.4`
* [ ] Merged updates to code (Java/FXML) files during the past 2 weeks (:exclamation: try to do by next milestone)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-W12-3/main/issues/101 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @okkhoy

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-06 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
