### ISSUE TITLE
Feedback on week 9 project progress for CS2113T-W12-3

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-W12-3/main#64]
## Team progress for `v1.2`
* [ ] Team PR created to the upstream repository with the title `[AY1920S1-CS2113T-W12-3] Contact List Pro`(:exclamation:)
* Milestone `v1.2` properly managed:
   * [x] A suitable deadline 2019-10-15 set(:heavy_check_mark: well done!)
   * [x] Issues allocated to it https://github.com/AY1920S1-CS2113T-W12-3/main/issues/62 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/61 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/36 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/34 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/16 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/15 (:heavy_check_mark: well done!)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [x] Milestone explicitly closed(:heavy_check_mark: well done!)
   * [x] Code tagged as `v1.2`(:heavy_check_mark: well done!)
* Milestones setup:
   * [x] Milestone `v1.2` setup(:heavy_check_mark: well done!)
   * [x] Milestone `v1.3` setup(:heavy_check_mark: well done!)
   * [x] Milestone `v1.4` setup(:heavy_check_mark: well done!)
* Milestone v1.3 planned:
   * [ ] A suitable deadline 2019-10-29 set(:exclamation:)
   * [x] Issues allocated to it https://github.com/AY1920S1-CS2113T-W12-3/main/issues/26 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/24 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/23 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/22 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/21 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/18 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/17 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/14 (:heavy_check_mark: well done!)
## Individual progress of @alex-teo for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-W12-3/main/issues/16 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/15 (:heavy_check_mark: well done!)
## Individual progress of @amirazhar for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-W12-3/main/issues/61 https://github.com/AY1920S1-CS2113T-W12-3/main/issues/34 (:heavy_check_mark: well done!)
## Individual progress of @amoschan97 for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-W12-3/main/issues/36 (:heavy_check_mark: well done!)
## Individual progress of @zkchang97 for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-W12-3/main/issues/62 (:heavy_check_mark: well done!)
## Individual progress of @wyinnnn for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [ ] Has issues/PRs assigned for `v1.2` milestone (:exclamation:)

Tutor: @okkhoy

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-10-16 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
